-- Migration: planned_outings_relations
-- Description: Create the planned_outings, planned_outing_participants, and planned_outing_activities tables

-- Table: planned_outings
CREATE TABLE IF NOT EXISTS planned_outings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add creator_id so the creator can fetch the row immediately after inserting it (bypassing the catch-22)
ALTER TABLE planned_outings ADD COLUMN IF NOT EXISTS creator_id UUID DEFAULT auth.uid();

-- Table: planned_outing_participants
CREATE TABLE IF NOT EXISTS planned_outing_participants (
    planned_outing_id BIGINT NOT NULL REFERENCES planned_outings(id) ON DELETE CASCADE,
    profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    PRIMARY KEY (planned_outing_id, profile_id)
);

-- Table: planned_outing_activities
CREATE TABLE IF NOT EXISTS planned_outing_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planned_outing_id BIGINT NOT NULL REFERENCES planned_outings(id) ON DELETE CASCADE,
    activity_id UUID NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    time TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0
);

-- Grant privileges to authenticated and anon roles so PostgREST can access the tables
GRANT SELECT, INSERT, UPDATE, DELETE ON planned_outings TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON planned_outing_participants TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON planned_outing_activities TO authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON planned_outings TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON planned_outing_participants TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON planned_outing_activities TO anon;

-- Row Level Security (RLS)
ALTER TABLE planned_outings ENABLE ROW LEVEL SECURITY;
ALTER TABLE planned_outing_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE planned_outing_activities ENABLE ROW LEVEL SECURITY;

-- Policies for planned_outings
DROP POLICY IF EXISTS "Users can view planned outings they participate in" ON planned_outings;
CREATE POLICY "Users can view planned outings they participate in" 
    ON planned_outings FOR SELECT 
    USING (
        creator_id = auth.uid() OR
        EXISTS (
            SELECT 1 FROM planned_outing_participants
            WHERE planned_outing_participants.planned_outing_id = planned_outings.id
            AND planned_outing_participants.profile_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Users can create planned outings" ON planned_outings;
CREATE POLICY "Users can create planned outings" 
    ON planned_outings FOR INSERT 
    WITH CHECK (auth.uid() IS NOT NULL);

-- Policies for planned_outing_participants
DROP POLICY IF EXISTS "Users can view participants of their planned outings" ON planned_outing_participants;
CREATE POLICY "Users can view participants of their planned outings" 
    ON planned_outing_participants FOR SELECT 
    USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Users can insert participants" ON planned_outing_participants;
CREATE POLICY "Users can insert participants" 
    ON planned_outing_participants FOR INSERT 
    WITH CHECK (auth.uid() IS NOT NULL);

-- Policies for planned_outing_activities
DROP POLICY IF EXISTS "Users can view activities of their planned outings" ON planned_outing_activities;
CREATE POLICY "Users can view activities of their planned outings" 
    ON planned_outing_activities FOR SELECT 
    USING (
        planned_outing_id IN (
            SELECT planned_outing_id FROM planned_outing_participants
            WHERE profile_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Users can insert activities" ON planned_outing_activities;
CREATE POLICY "Users can insert activities" 
    ON planned_outing_activities FOR INSERT 
    WITH CHECK (auth.uid() IS NOT NULL);
